<?php
return array (
  8 => 
  array (
    'groupid' => '8',
    'name' => '游客',
    'issystem' => '0',
    'starnum' => '0',
    'point' => '0',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '1',
    'allowupgrade' => '0',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '',
    'sort' => '0',
    'disabled' => '0',
  ),
  4 => 
  array (
    'groupid' => '4',
    'name' => 'A级至尊版',
    'issystem' => '0',
    'starnum' => '2',
    'point' => '500',
    'allowmessage' => '150',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '1',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '300.00',
    'price_m' => '30.00',
    'price_d' => '1.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '',
    'sort' => '6',
    'disabled' => '0',
  ),
  2 => 
  array (
    'groupid' => '2',
    'name' => 'C级攻击版',
    'issystem' => '0',
    'starnum' => '3',
    'point' => '150',
    'allowmessage' => '500',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '1',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '500.00',
    'price_m' => '60.00',
    'price_d' => '1.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '',
    'sort' => '4',
    'disabled' => '0',
  ),
  3 => 
  array (
    'groupid' => '3',
    'name' => 'B级机构版',
    'issystem' => '0',
    'starnum' => '5',
    'point' => '300',
    'allowmessage' => '999',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '1',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '360.00',
    'price_m' => '90.00',
    'price_d' => '5.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '',
    'sort' => '5',
    'disabled' => '0',
  ),
  1 => 
  array (
    'groupid' => '1',
    'name' => '禁止访问',
    'issystem' => '0',
    'starnum' => '0',
    'point' => '0',
    'allowmessage' => '0',
    'allowvisit' => '0',
    'allowpost' => '0',
    'allowpostverify' => '0',
    'allowsearch' => '0',
    'allowupgrade' => '0',
    'allowsendmessage' => '0',
    'allowpostnum' => '0',
    'allowattachment' => '0',
    'price_y' => '0.00',
    'price_m' => '0.00',
    'price_d' => '0.00',
    'icon' => '',
    'usernamecolor' => '',
    'description' => '0',
    'sort' => '0',
    'disabled' => '0',
  ),
);
?>